name: Release macOS Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Format and vet
        run: gofmt -l . && go vet ./...

      - name: Run tests
        run: go test -coverprofile=coverage.out ./...

      - name: Ensure coverage threshold
        run: |
          go tool cover -func=coverage.out | awk '/total:/ {gsub("%", "", $3); coverage=$3} END {\
            if (coverage == "") {\
              printf "Failed to parse total coverage.\n";\
              exit 1;\
            }\
            printf "Total coverage: %s%%\n", coverage;\
            if (coverage + 0 < 80) {\
              printf "Coverage %.2f%% is below required 80%%.\n", coverage;\
              exit 1;\
            }\
          }'

      - name: Build binary
        run: go build -o ./bin/ccs ./cmd/ccs

      - name: Archive
        run: tar -czf ccs-macos-amd64.tar.gz ./bin

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: ccs-macos-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
