name: Release macOS Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Format and vet
        run: |
          gofmt -l .
          go vet ./...

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Enforce coverage threshold
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}')
          percent=${coverage%%%}
          awk -v p="$percent" 'BEGIN { if (p < 80) { printf "Coverage %s is below 80%%\n", p; exit 1 } }'

      - name: Build binary
        run: go build -o ccs ./cmd/ccs

      - name: Create archive
        run: tar -czf ccs-macos-amd64.tar.gz ccs

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: ccs-macos-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
